// 要加就按照 { text: "名句", author: "名句作者" }, 来写，不如绝对报错
const quotes = [
  { text: "学而不思则罔，思而不学则殆。", author: "孔子" },
  { text: "己所不欲，勿施于人。", author: "孔子" },
  { text: "路漫漫其修远兮，吾将上下而求索。", author: "屈原" },
  { text: "人生自古谁无死，留取丹心照汗青。", author: "文天祥" },
  { text: "此情可待成追忆，只是当时已惘然。", author: "李商隐" },
  { text: "只有弱者和懦夫才说暴力解决不了任何问题", author: "路易吉" },
  { text: "会当凌绝顶，一览众山小。", author: "杜甫" },
  { text: "中国的教育无疑是成功的 因为它几乎让每一位未成年都像哲学家思考起活着的意义。", author: "抖音用户" },
  { text: "落霞与孤鹜齐飞，秋水共长天一色。", author: "王勃" },
  { text: "采菊东篱下，悠然见南山。", author: "陶渊明" },
  { text: "天行健，君子以自强不息。", author: "《周易》" },
  { text: "欲穷千里目，更上一层楼。", author: "王之涣" },
  { text: "朋友还是敌人？选吧", author: "凯文" },
  { text: "中国的教育无疑是成功的 因为它几乎让每一位未成年都像哲学家思考起活着的意义。", author: "抖音用户" },
  { text: "不畏浮云遮望眼，自缘身在最高层。", author: "王安石" },
  { text: "横眉冷对千夫指，俯首甘为孺子牛。", author: "鲁迅" },
  { text: "希望是附丽在存在上的，有存在，便有希望，有希望，便是光明。", author: "鲁迅" },
  { text: "世界上本没有路，走的人多了，也便成了路。", author: "鲁迅" },
  { text: "有志者事竟成。", author: "李密" },
  { text: "天将降大任于斯人也，必先苦其心志，劳其筋骨。", author: "孟子" },
  { text: "千里之行，始于足下。", author: "老子" },
  { text: "大道之行也，天下为公。", author: "礼记" },
  { text: "读万卷书，行万里路。", author: "刘彝" },
  { text: "纸上得来终觉浅，绝知此事要躬行。", author: "陆游" },
  { text: "我自横刀向天笑，去留肝胆两昆仑。", author: "谭嗣同" },
  { text: "天高任鸟飞，海阔凭鱼跃。", author: "古语" },
  { text: "愿你出走半生，归来仍是少年。", author: "刘励" },
  { text: "莫等闲，白了少年头，空悲切。", author: "岳飞" },
  { text: "长风破浪会有时，直挂云帆济沧海。", author: "李白" },
  { text: "举杯邀明月，对影成三人。", author: "李白" },
  { text: "清风不问旅人苦，明月自知别离情。", author: "现代俗语" },
  { text: "有花堪折直须折，莫待无花空折枝。", author: "杜秋娘" },
  { text: "感时花溅泪，恨别鸟惊心。", author: "杜甫" },
  { text: "昨夜西风凋碧树，独上高楼，望尽天涯路。", author: "柳永" },
  { text: "人生如逆旅，我亦是行人。", author: "苏轼" },
  { text: "但愿人长久，千里共婵娟。", author: "苏轼" },
  { text: "人生得意须尽欢，莫使金樽空对月。", author: "李白" },
  { text: "海内存知己，天涯若比邻。", author: "王勃" },
  { text: "苟日新，日日新，又日新。", author: "《礼记·大学》" },
  { text: "中国的教育无疑是成功的 因为它几乎让每一位未成年都像哲学家思考起活着的意义。", author: "抖音用户" },
  { text: "不积跬步，无以至千里。", author: "荀子" },
  { text: "路遥知马力，日久见人心。", author: "古语" },
  { text: "知之者不如好之者，好之者不如乐之者。", author: "孔子" },
  { text: "学而时习之，不亦说乎？", author: "孔子" },
  { text: "夫君子之行，静以修身，俭以养德。", author: "诸葛亮" },
  { text: "既来之，则安之。", author: "《论语》" },
  { text: "不以物喜，不以己悲。", author: "范仲淹" },
  { text: "我们唯一要害怕的，就是害怕本身。", author: "罗斯福" },
  { text: "生存还是毁灭，这是一个问题。", author: "莎士比亚" },
  { text: "整个世界是一个舞台，所有的人都只是演员。", author: "莎士比亚" },
  { text: "林中有两条路，而我选择了人迹更少的一条。", author: "罗伯特·弗罗斯特" },
  { text: "用三句话概括我对人生的理解：生活还要继续。", author: "罗伯特·弗罗斯特" },
  { text: "漂泊的人未必迷失方向。", author: "托尔金" },
  { text: "真正的智慧在于知道自己无知。", author: "苏格拉底" },
  { text: "我思故我在。", author: "笛卡尔" },
  { text: "成为你希望看到的世界的改变。", author: "甘地" },
  { text: "当你忙着制定人生计划时，生活正在发生。", author: "约翰·列侬" },
  { text: "未经审视的人生不值得过。", author: "苏格拉底" },
  { text: "幸福不是现成的，它来自你的行动。", author: "达赖喇嘛" },
  { text: "生命中最伟大的荣耀，不在于从未跌倒，而在于每次跌倒后都能站起。", author: "曼德拉" },
  { text: "在困难的中心孕育着机遇。", author: "爱因斯坦" },
  { text: "想象力比知识更重要。", author: "爱因斯坦" },
  { text: "只要我们不怀疑今天，就没有实现不了的明天。", author: "罗斯福" },
  { text: "永远面向阳光，阴影就会落在你身后。", author: "惠特曼" },
  { text: "我们所想的，会成为我们自己。", author: "佛陀" },
  { text: "不要走别人走过的路，要走没有路的地方，留下你的足迹。", author: "爱默生" },
  { text: "活着是世上最罕见的事，大多数人只是存在而已。", author: "王尔德" },
  { text: "做你自己，因为别人都已经有人做了。", author: "王尔德" },
  { text: "我们都生活在阴沟里，但仍有人仰望星空。", author: "王尔德" },
  { text: "没有书的房间，就像没有灵魂的身体。", author: "西塞罗" },
  { text: "预测未来的最好方式就是创造未来。", author: "阿兰·凯" },
  { text: "成功不是终点，失败也非末日，继续前行的勇气才最重要。", author: "丘吉尔" },
  { text: "如果你正在经历地狱，那就继续前进。", author: "丘吉尔" },
  { text: "不相信魔法的人，永远不会发现魔法。", author: "罗尔德·达尔" },
  { text: "我们接受自己认为配得上的爱。", author: "斯蒂芬·切波斯基" },
  { text: "你只活一次，但如果你活得精彩，一次足矣。", author: "梅·韦斯特" },
  { text: "我们生活的目的就是追求幸福。", author: "达赖喇嘛" },
  { text: "尽你所能，利用你所拥有的，在你所在之处行动。", author: "西奥多·罗斯福" },
  { text: "成为你本可以成为的人，永远不嫌晚。", author: "乔治·艾略特" },
  { text: "内心藏着未诉的故事，是一种最大的痛苦。", author: "玛雅·安吉洛" },
  { text: "想走得快，就一个人走；想走得远，就一起走。", author: "非洲谚语" },
  { text: "一切你能想象的，都是真实的。", author: "毕加索" },
  { text: "成就伟大工作的唯一方式，是热爱你所做的事。", author: "乔布斯" },
  { text: "求知若饥，虚心若愚。", author: "乔布斯" },
  { text: "勇气并不总是咆哮，有时它是一天结束时轻声说的：明天我会再试一次。", author: "玛丽·安妮·拉德马赫" },
  { text: "你错过的投篮，是你没有出手的那一球。", author: "韦恩·格雷茨基" },
  { text: "行动时要相信，你的努力正在产生影响。", author: "威廉·詹姆斯" },
  { text: "未来属于那些相信梦想之美的人。", author: "埃莉诺·罗斯福" },
  { text: "幸运偏爱勇敢的人。", author: "拉丁谚语" },
  { text: "人非圣贤，孰能无过？能原谅，方为宽容。", author: "蒲柏" },
  { text: "像明天就要死去那样生活，像永远活着那样学习。", author: "甘地" },
  { text: "唯一不可能的旅程，是你从未开始的旅程。", author: "托尼·罗宾斯" }
];


// 要改背景就放在images文件夹，文件名称就是下面的图片“bg1.jpg”
const backgroundImage = "images/bg1.jpg";
// 固定背景和随机名言，不用管
function showQuoteAndBackground() {
  const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
  
  document.getElementById("quote").textContent = randomQuote.text;
  document.getElementById("author").textContent = `—— ${randomQuote.author}`;
  
  document.body.style.backgroundImage = `url('${backgroundImage}')`;
}

showQuoteAndBackground();
